### EDA Proveedores, Concepto

In [2]:
import pandas as pd
pd.show_versions()

d:\Anaconda\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit              : a60ad39b4a9febdea9a59d602dad44b1538b0ea5
python              : 3.10.12.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.26100
machine             : AMD64
processor           : AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : es_ES.cp1252

pandas              : 2.1.2
numpy               : 1.25.2
pytz                : 2022.7
dateutil            : 2.8.2
setuptools          : 65.6.3
pip                 : 24.0
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : 5.1.0
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.17.2
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.8.2
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 14.0.1
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.1
sqlalchemy          : 2.0.23
tables              : None
tabulate            : 0.9.0
xarray              : None
xlrd                : None
zstandard           : 0.19.0
tzdata              : 2023.3
qtpy                : 2.2.0
pyqt5               : None

In [3]:
# Usando raw string (recomendado en Windows)
tabla = pd.read_csv(r"C:\Users\rfigu\Documents\Learn\CursoDA_de1hora5\BasesEjemplo\TablaEjemplo.csv" ## VentasPorProveedor.csv"
                    , sep=",")
                    #,skiprows=5)
tabla.head()

  Nombre  Edad       País Automovil
0   Juan    35     México        No
1  Pedro    41     España        Si
2  María    28       Perú        Si
3  Laura    66  Argentina        No

In [4]:
##leer una serie especifica, siempre y cuando no tenga espacio em el nombre
tabla.Edad

0    35
1    41
2    28
3    66
Name: Edad, dtype: int64

In [5]:
## leer varias serie a la vez se utiliza 2 corchetes
tabla[['Edad','País']]

   Edad       País
0    35     México
1    41     España
2    28       Perú
3    66  Argentina

In [6]:
# al invocar una serie, te detalla el tipo de objeto
tabla['Nombre']

0     Juan
1    Pedro
2    María
3    Laura
Name: Nombre, dtype: object

In [7]:
# Type me indica que tipo 
#  cuando tomo 1 columnas me devuel SERIE
type(tabla.Edad)

pandas.core.series.Series

In [8]:
# Si tomo 2 ya se convierte en DataFrame
type(tabla[['Edad','País']])

pandas.core.frame.DataFrame

In [10]:
VentasPorProveedor = pd.read_csv(r"C:\Users\rfigu\Documents\Learn\CursoDA_de1hora5\BasesEjemplo\VentasPorProveedor.csv" ## TablaEjemplo.csv"
                    , sep=";"
                    ,skiprows=5)
VentasPorProveedor.head() ## Sirve para visualizar las 1ras 5 lineas de tu DataFrame

,Fecha,Vendedor,Región,Artículo,Categoría,Unidades,Ganancia
0,1/1/2016,Steve Ashton,Norte,Medias Femeninas,Vestimenta,6,"18,00"
1,1/1/2016,Trevor Snodgrass,Oeste,Chocolate,Comestibles,8,"3,84"
2,1/1/2016,Sarah Bond,Sur,Gorras,Vestimenta,3,"6,30"
3,1/1/2016,Desmond Delaney,Sur,Sánguche de Queso,Comestibles,9,"14,40"
4,1/1/2016,Desmond Delaney,Este,Chocolate,Comestibles,14,"6,72"

In [ ]:
## el resumen de tu datadrame, tipo datos, nro de filas y nulos
VentasPorProveedor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460 entries, 0 to 459
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Fecha      460 non-null    object
 1   Vendedor   460 non-null    object
 2   Región     460 non-null    object
 3   Artículo   460 non-null    object
 4   Categoría  460 non-null    object
 5   Unidades   460 non-null    int64
 6   Ganancia   460 non-null    object
dtypes: int64(1), object(6)
memory usage: 25.3+ KB